// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxr1ZWjDNWOcnwWFBsb8A57QM39p8Zex0',
    appId: '1:619975423102:android:5be248f9d98f32e15d142f',
    messagingSenderId: '619975423102',
    projectId: 'mynote-first-project',
    storageBucket: 'mynote-first-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiD6W6KVNRvXnjUh1VLi3O8xIKSvMjHtI',
    appId: '1:619975423102:ios:28c5cd82f89ff0035d142f',
    messagingSenderId: '619975423102',
    projectId: 'mynote-first-project',
    storageBucket: 'mynote-first-project.appspot.com',
    iosClientId: '619975423102-tdapbkcf3d9g7hpcp4u7f4v5r6u9eiqj.apps.googleusercontent.com',
    iosBundleId: 'ir.mobin.mynote',
  );
}
